### Status Bar:
#
# Read `man 5 sway-bar` for more information about this section.
bar {
swaybar_command waybar
mode dock
}

### Idle configuration

exec swayidle -w \
timeout 300 '/home/juan/.config/sway/scripts/lock.sh' \
timeout 600 'swaymsg "output * power off"' \
resume 'swaymsg "output * power on"' \
before-sleep '/home/juan/.config/sway/scripts/lock.sh'

# Environment variables for XWayland apps (Steam, etc.)
exec --no-startup-id export GDK_SCALE=2 GDK_DPI_SCALE=0.5 XCURSOR_SIZE=32

# The following daemon is used for notifications (e.g. mako, swaync)
exec mako

# Waybar
exec waybar

# Autotiling
exec_always ~/.config/sway/scripts/autotiling.sh

# Clipboard history
exec wl-paste --watch cliphist store

# Polkit authentication agent
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
