### Variables
# command as mod key
set $mod Mod4

# monitor names
set $LG_monitor DP-4
set $HP_monitor DP-1
set $IIYAMA_monitor HDMI-A-1

# Home row direction keys, like vim
set $left h
set $down n
set $up e
set $right i

# Your preferred terminal emulator
set $term ghostty

# Your preferred application launcher
set $menu wofi --show drun
