### Visuals
# Gaps
gaps inner 10
gaps outer 10

# Focus follows mouse (Aerospace-style)
focus_follows_mouse yes

# SwayFX visuals
corner_radius 10
shadows enable
shadow_blur_radius 30
shadow_color             #000000aa
blur enable
default_dim_inactive 0.2

# Borders
default_border pixel 2
default_floating_border pixel 2

# Smart gaps (gaps used if only more than one container on the workspace)
smart_gaps off

# Colors
# class                 border  backgr. text    indicator child_border
client.focused          #76cce0 #502c2e #ffffff #2e9ef4   #76cce0
client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
client.unfocused        #333333 #222222 #888888 #292d2e   #222222
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c
client.background       #ffffff
